server:
  port: 8090

spring:
  cloud:
    gateway:
      routes:
#      - id: path_route
#        uri: http://localhost:8123
#        predicates:
#        - Path=/api/**
      - id: api2_route
        uri: http://localhost:8123
        predicates:
        - Path=/api2/**

logging:
  level:
    org.springframework.cloud.gateway: trace

dubbo:
  application:
    name: dubbo-consumer
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://localhost:8848