
spring:
  cloud:
    gateway:
      routes:
#      - id: path_route
#        uri: http://localhost:8123
#        predicates:
#        - Path=/api/**
      - id: api2_route
        uri: http://8.130.76.170:8123
        predicates:
        - Path=/api2/**

logging:
  level:
    org.springframework.cloud.gateway: trace

dubbo:
  application:
    name: dubbo-consumer
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://8.130.76.170:8848

ini:
  gateway:
    api-host: http://8.130.76.170:8090